import React from "react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Building2, Globe, Users, Cpu, FileText, Newspaper } from "lucide-react";
export const CompanyInsightCard = ({ company }) => {
  if (!company) return null;
  return /* @__PURE__ */ React.createElement(Card, { className: "border border-zinc-800 bg-zinc-950/60 backdrop-blur-md" }, /* @__PURE__ */ React.createElement(CardHeader, { className: "pb-3 border-b border-zinc-900" }, /* @__PURE__ */ React.createElement(CardTitle, { className: "text-lg font-bold flex items-center gap-2 text-zinc-100" }, /* @__PURE__ */ React.createElement(Building2, { className: "h-5 w-5 text-primary" }), /* @__PURE__ */ React.createElement("span", null, company.name, " Intelligence"))), /* @__PURE__ */ React.createElement(CardContent, { className: "pt-4 space-y-5 text-sm text-zinc-300" }, /* @__PURE__ */ React.createElement("div", { className: "grid grid-cols-3 gap-3 text-xs" }, /* @__PURE__ */ React.createElement("div", { className: "space-y-1" }, /* @__PURE__ */ React.createElement("span", { className: "text-zinc-500 font-bold uppercase tracking-wider block text-[10px]" }, "Industry"), /* @__PURE__ */ React.createElement("span", { className: "text-zinc-300 font-medium truncate block" }, company.industry || "Not specified")), /* @__PURE__ */ React.createElement("div", { className: "space-y-1" }, /* @__PURE__ */ React.createElement("span", { className: "text-zinc-500 font-bold uppercase tracking-wider block text-[10px]" }, "Website"), company.website ? /* @__PURE__ */ React.createElement(
    "a",
    {
      href: company.website.startsWith("http") ? company.website : `https://${company.website}`,
      target: "_blank",
      rel: "noopener noreferrer",
      className: "text-primary hover:underline flex items-center gap-0.5 truncate block"
    },
    /* @__PURE__ */ React.createElement(Globe, { className: "h-3 w-3 inline" }),
    " ",
    company.website.replace(/(^\w+:|^)\/\//, "")
  ) : /* @__PURE__ */ React.createElement("span", { className: "text-zinc-500 italic block" }, "Not specified")), /* @__PURE__ */ React.createElement("div", { className: "space-y-1" }, /* @__PURE__ */ React.createElement("span", { className: "text-zinc-500 font-bold uppercase tracking-wider block text-[10px]" }, "Company Size"), /* @__PURE__ */ React.createElement("div", { className: "flex items-center gap-1 text-zinc-300" }, /* @__PURE__ */ React.createElement(Users, { className: "h-3.5 w-3.5 text-zinc-500" }), /* @__PURE__ */ React.createElement("span", { className: "truncate" }, company.companySize || "Unknown")))), /* @__PURE__ */ React.createElement("div", { className: "p-3 rounded-lg bg-zinc-900/40 border border-zinc-900 text-xs leading-relaxed" }, /* @__PURE__ */ React.createElement("h5", { className: "font-bold text-zinc-200 mb-1 flex items-center gap-1" }, /* @__PURE__ */ React.createElement(FileText, { className: "h-3.5 w-3.5 text-zinc-500" }), " Personalization Context"), /* @__PURE__ */ React.createElement("p", { className: "text-zinc-400 italic" }, '"', company.insightSummary, '"')), (company.products.length > 0 || company.services.length > 0) && /* @__PURE__ */ React.createElement("div", { className: "space-y-2" }, /* @__PURE__ */ React.createElement("h5", { className: "text-xs font-bold uppercase tracking-wider text-zinc-500" }, "Key Offerings"), /* @__PURE__ */ React.createElement("div", { className: "flex flex-wrap gap-1" }, [...company.products, ...company.services].map((offering, idx) => /* @__PURE__ */ React.createElement(Badge, { key: idx, variant: "outline", className: "border-zinc-800 bg-zinc-900/30 text-zinc-400 text-[10px]" }, offering)))), company.techStack.length > 0 && /* @__PURE__ */ React.createElement("div", { className: "space-y-2" }, /* @__PURE__ */ React.createElement("h5", { className: "text-xs font-bold uppercase tracking-wider text-zinc-500 flex items-center gap-1" }, /* @__PURE__ */ React.createElement(Cpu, { className: "h-3.5 w-3.5 text-zinc-500" }), " Tech Stack"), /* @__PURE__ */ React.createElement("div", { className: "flex flex-wrap gap-1" }, company.techStack.map((tech, idx) => /* @__PURE__ */ React.createElement(Badge, { key: idx, variant: "secondary", className: "bg-zinc-900 text-zinc-300 border-none text-[10px]" }, tech)))), company.recentNews.length > 0 && /* @__PURE__ */ React.createElement("div", { className: "space-y-2 pt-2 border-t border-zinc-900/50" }, /* @__PURE__ */ React.createElement("h5", { className: "text-xs font-bold uppercase tracking-wider text-zinc-500 flex items-center gap-1" }, /* @__PURE__ */ React.createElement(Newspaper, { className: "h-3.5 w-3.5 text-zinc-500" }), " Factual Context & News"), /* @__PURE__ */ React.createElement("ul", { className: "list-disc list-inside space-y-1 text-xs text-zinc-400" }, company.recentNews.map((news, idx) => /* @__PURE__ */ React.createElement("li", { key: idx, className: "leading-relaxed" }, news))))));
};
