import { Router } from "express";
import { getEmails, getEmailById, deleteEmail, getStats, getTemplates } from "../controllers/emailController.js";
import { auth } from "../middleware/auth.js";
const router = Router();
router.get("/stats", auth, getStats);
router.get("/templates", auth, getTemplates);
router.get("/", auth, getEmails);
router.get("/:id", auth, getEmailById);
router.delete("/:id", auth, deleteEmail);
export default router;
