import { Router } from "express";
import { getTrackedJobs, addTrackedJob, updateTrackerStatus, getAnalytics, deleteTrackerEntry } from "../controllers/trackerController.js";
import { auth } from "../middleware/auth.js";
const router = Router();
router.use(auth);
router.get("/", getTrackedJobs);
router.post("/", addTrackedJob);
router.patch("/:id/status", updateTrackerStatus);
router.get("/analytics", getAnalytics);
router.delete("/:id", deleteTrackerEntry);
export default router;
